name = "UFC 324"
date = "2026-01-24"
location = "Las Vegas, Nevada"
venue = "T-Mobile Arena"

[[fights]]
order = 1 # main event

[fights.fighter_a]
name = "Justin Gaethje"
record = "26-5-0"
ranking = "4"
lastFive = "W L W W L"
division = "Lightweight"
type = "Striker"
odds = +200


[fights.fighter_b]
name = "Paddy Pimblett"
record = "23-3-0"
ranking = "5"
lastFive = "W W W W W"
division = "Lightweight"
type = "Grappler"
odds = -250

[[fights]]
order = 2 # co-main event

[fights.fighter_a]
name = "Sean O'Malley"
record = "18-3-0"
ranking = "3"
lastFive = "L L W W W"
division = "Bantamweight"
type = "Striker"
odds = -220


[fights.fighter_b]
name = "Yadong Song"
record = "22-8-1"
ranking = "5"
lastFive = "W L W W L"
division = "Bantamweight"
type = "Striker"
odds = +180

[[fights]]
order = 3

[fights.fighter_a]
name = "Waldo Cortes-Acosta"
record = "16-2-0"
ranking = "5"
lastFive = "W W L W W"
division = "Heavyweight"
type = "Striker"
odds = -325


[fights.fighter_b]
name = "Derrick Lewis"
record = "29-12-0"
ranking = "8"
lastFive = "W W L W L"
division = "Heavyweight"
type = "Striker"
odds = +260

[[fights]]
order = 4

[fights.fighter_a]
name = "Natalia Silva"
record = "19-5-1"
ranking = "2"
lastFive = "W W W W W"
division = "Flyweight"
type = "Striker"
odds = -320


[fights.fighter_b]
name = "Rose Namajunas"
record = "14-7-0"
ranking = "6"
lastFive = "W L W W L"
division = "Flyweight"
type = "Striker"
odds = +250

[[fights]]
order = 5 # main card opener

[fights.fighter_a]
name = "Arnold Allen"
record = "20-3-0"
ranking = "6"
lastFive = "W L L W W"
division = "Featherweight"
type = "Striker"
odds = +190


[fights.fighter_b]
name = "Jean Silva"
record = "16-3-0"
ranking = "10"
lastFive = "L W W W W"
division = "Featherweight"
type = "Striker"
odds = -235

[[fights]]
order = 6

[fights.fighter_a]
name = "Umar Nurmagomedov"
record = "19-1-0"
ranking = "2"
lastFive = "W L W W W"
division = "Bantamweight"
type = "Grappler"
odds = -1600


[fights.fighter_b]
name = "Deiveson Figueiredo"
record = "25-5-1"
ranking = "6"
lastFive = "W L L W W"
division = "Bantamweight"
type = "Hybrid"
odds = +900

[[fights]]
order = 7

[fights.fighter_a]
name = "Ateba Gautier"
record = "9-1-0"
ranking = "NR"
lastFive = "W W W W W"
division = "Middleweight"
type = "Striker"
odds = -1000


[fights.fighter_b]
name = "Andrey Pulyaev"
record = "10-3-0"
ranking = "NR"
lastFive = "W L W W W"
division = "Middleweight"
type = "Striker"
odds = +650

[[fights]]
order = 8

[fights.fighter_a]
name = "Nikita Krylov"
record = "30-11-0"
ranking = "13"
lastFive = "L L W W W"
division = "Light Heavyweight"
type = "Hybrid"
odds = +115


[fights.fighter_b]
name = "Modestas Bukauskas"
record = "19-6-0"
ranking = "NR"
lastFive = "W W W W L"
division = "Light Heavyweight"
type = "Striker"
odds = -135

[[fights]]
order = 9

[fights.fighter_a]
name = "Alex Perez"
record = "25-10-0"
ranking = "11"
lastFive = "L L W L L"
division = "Flyweight"
type = "Striker"
odds = +145


[fights.fighter_b]
name = "Charles Johnson"
record = "18-7-0"
ranking = "13"
lastFive = "W L W W W"
division = "Flyweight"
type = "Striker"
odds = -170

[[fights]]
order = 10

[fights.fighter_a]
name = "Josh Hokit"
record = "7-0-0"
ranking = "NR"
lastFive = "W W W W W"
division = "Heavyweight"
type = "Striker"
odds = -275


[fights.fighter_b]
name = "Denzel Freeman"
record = "7-1-0"
ranking = "NR"
lastFive = "W W W L W"
division = "Heavyweight"
type = "Striker"
odds = +220

[[fights]]
order = 11

[fights.fighter_a]
name = "Ty Miller"
record = "6-0-0"
ranking = "NR"
lastFive = "W W NC W W"
division = "Welterweight"
type = "Striker"
odds = -450


[fights.fighter_b]
name = "Adam Fugitt"
record = "16-3-0"
ranking = "NR"
lastFive = "L L W L W"
division = "Welterweight"
type = "Striker"
odds = +340
